/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as SwDotjsRouteImport } from './routes/sw[.]js'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const SwDotjsRoute = SwDotjsRouteImport.update({
  id: '/sw.js',
  path: '/sw.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/sw.js': typeof SwDotjsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/sw.js': typeof SwDotjsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/sw.js': typeof SwDotjsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/manifest.json'
    | '/manifest.webmanifest'
    | '/sw.js'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/manifest.json'
    | '/manifest.webmanifest'
    | '/sw.js'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/manifest.json'
    | '/manifest.webmanifest'
    | '/sw.js'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  SwDotjsRoute: typeof SwDotjsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sw.js': {
      id: '/sw.js'
      path: '/sw.js'
      fullPath: '/sw.js'
      preLoaderRoute: typeof SwDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  SwDotjsRoute: SwDotjsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
